kind: Pod
apiVersion: v1
metadata:
  name: csi-linux-pod
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - image: k8s.gcr.io/e2e-test-images/busybox:1.29
      name: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "appconfig-spc"
        nodePublishSecretRef:
          name: appconfig-creds
  nodeSelector:
    kubernetes.io/os: linux
