apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: appconfig-spc
spec:
  provider: azure
  parameters:
    kvs: |
      array:
        - |
          key: key1
          label: dev
